attribute = "#8ec07c"
"constant.numeric" = "#d3869b"
"diff.delta" = "#fe8019"
"diff.delta.moved" = "#8ec07c"
"diff.minus" = "#fb4934"
"diff.plus" = "#b8bb26"
"function.builtin" = "#fabd2f"
"function.macro" = "#8ec07c"
"keyword.directive" = "#cc241d"
label = "#8ec07c"
"markup.heading" = "#8ec07c"
"markup.link.text" = "#fb4934"
"markup.raw" = "#fb4934"
module = "#8ec07c"
namespace = "#8ec07c"
operator = "#d3869b"
punctuation = "#fe8019"
"punctuation.delimiter" = "#fe8019"
special = "#b16286"
string = "#b8bb26"
tag = "#fb4934"
type = "#fabd2f"
"type.builtin" = "#fabd2f"
variable = "#ebdbb2"
"variable.builtin" = "#fe8019"
"variable.other.member" = "#83a598"
"variable.parameter" = "#d5c4a1"

[comment]
fg = "#928374"
modifiers = ["italic"]

[constant]
fg = "#d3869b"

["constant.builtin"]
fg = "#d3869b"
modifiers = ["bold"]

["constant.character.escape"]
fg = "#d5c4a1"
modifiers = ["bold"]

[constructor]
fg = "#d3869b"
modifiers = ["bold"]

[diagnostic]
modifiers = ["underlined"]

["diagnostic.error"]
bg = "#1d2021"
fg = "#fb4934"

["diagnostic.hint"]
bg = "#1d2021"
fg = "#fabd2f"

["diagnostic.info"]
bg = "#1d2021"
fg = "#8ec07c"

["diagnostic.warning"]
bg = "#1d2021"
fg = "#fe8019"

[error]
bg = "#1d2021"
fg = "#fb4934"

[function]
fg = "#b8bb26"
modifiers = ["bold"]

[hint]
bg = "#1d2021"
fg = "#83a598"

[info]
bg = "#1d2021"
fg = "#8ec07c"

[keyword]
fg = "#fb4934"

["markup.bold"]
modifiers = ["bold"]

["markup.italic"]
modifiers = ["italic"]

["markup.link.url"]
fg = "#b8bb26"
modifiers = ["underlined"]

["ui.background"]
bg = "#1d2021"

["ui.background.separator"]
fg = "#7c6f64"

["ui.cursor.insert"]
fg = "#83a598"

["ui.cursor.match"]
bg = "#665c54"

["ui.cursor.primary"]
modifiers = ["reversed"]

["ui.cursor.select"]
bg = "#928374"
fg = "#928374"

["ui.help"]
bg = "#282828"
fg = "#ebdbb2"

["ui.linenr"]
fg = "#665c54"

["ui.linenr.selected"]
fg = "#fabd2f"

["ui.menu"]
bg = "#3c3836"
fg = "#d5c4a1"

["ui.menu.selected"]
bg = "#83a598"
fg = "#3c3836"
modifiers = ["bold"]

["ui.popup"]
bg = "#3c3836"

["ui.popup.info"]
bg = "#282828"

["ui.selection"]
bg = "#665c54"

["ui.selection.primary"]
bg = "#665c54"

["ui.statusline"]
bg = "#3c3836"
fg = "#a89984"

["ui.statusline.inactive"]
bg = "#282828"
fg = "#928374"

["ui.text"]
fg = "#ebdbb2"

["ui.text.focus"]
fg = "#d3869b"

["ui.text.info"]
fg = "#ebdbb2"

["ui.virtual.ruler"]
bg = "#282828"

["ui.window"]
bg = "#282828"
fg = "#3c3836"

[warning]
bg = "#1d2021"
fg = "#fe8019"
