#!/bin/sh

youtube-dl  --audio-quality 0 \
--ignore-errors \
--extract-audio \
--audio-format mp3 \
--output "~/Media/Music/%(title)s.%(ext)s" \
--add-metadata \
--embed-thumbnail \
--metadata-from-title "%(artist)s - %(title)s" \
"$QUTE_URL"
